spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/recipes_database
    username: root
    password: 1qaz!QAZ
  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


